name: Build dist
on:
  workflow_dispatch:
    inputs:
      args:
        description: "API DOMAIN"
        required: false
        default: ""

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8.6.1"
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
      - name: Set env
        if: ${{ github.event.inputs.args != '' }}
        run: |
          echo "VITE_DOMAIN=${{ github.event.inputs.args }}" >> .env.production.local
      - name: Build
        run: pnpm build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 1
